added insertion_sort
FerdausPolok/dev-mates pull request #23
Opened 2024-10-02 14:48 UTC by Aditya-NV-06

2024-10-02 17:04 UTC, FerdausPolok reviewed
Hello @Aditya-NV-06!
Is this PR up for review? Could you please add a short description? Also your title says adding only about insertion_sort but I can see file chnages are beyond insertion_sort. Thanks.

2024-10-02 17:18 UTC, FerdausPolok requested changes
Please also add EOL (end of line) to all of the files. Thanks.

2024-10-02 17:20 UTC, Aditya-NV-06 commented
can you elaborate the changes you want to make in this repo

2024-10-02 17:28 UTC, Aditya-NV-06 commented
made the changes to the files

2024-10-02 17:46 UTC, FerdausPolok requested changes

2024-10-02 17:46 UTC, FerdausPolok commented on algorithm/sorting-algo-python/bucket_sort.py
> +#end of the line
By EOL we mostly refer to an empty new line at the bottom of the files.
If you do so, you no longer see the red circled minus (-) icon in GitHub file changes.
![image](https://github.com/user-attachments/assets/189ff87a-6dfd-4f7f-a635-99492a9563de)

```suggestion
    sorted_arr = bucket_sort(arr)
    print("Sorted array:", sorted_arr)

```

2024-10-02 17:46 UTC, FerdausPolok commented on algorithm/sorting-algo-python/heap_sort.py
> +#end of the line
Ditto.

FYI: By ditto we simple mean "Please do the same here as well"

2024-10-02 17:46 UTC, FerdausPolok commented on algorithm/sorting-algo-python/insertion_sort.py
> +#end of the line
ditto

2024-10-02 17:46 UTC, FerdausPolok commented on algorithm/sorting-algo-python/quick_sort.py
> +#end of the line
ditto

2024-10-02 17:46 UTC, FerdausPolok commented on algorithm/sorting-algo-python/radix_sort.py
> +#end of the line
ditto

2024-10-02 17:58 UTC, Aditya-NV-06 commented
changes are made in the files

2024-10-02 18:09 UTC, aditya-nv-06 commented
Correctly refactored the code this time as you said to me.

2024-10-03 00:10 UTC, FerdausPolok approved these changes
LGTM 🚀

2024-10-03 00:43 UTC, merged