Added session manager
FerdausPolok/dev-mates pull request #24
Opened 2024-10-02 14:52 UTC by tanushrigoel

I have added a utility tool for developers which help them manage their productivity better. This is my first time creating a pull request please guide me incase of any error or anything

2024-10-02 16:59 UTC, FerdausPolok requested changes
Hello @tanushrigoel! Thanks for your contribution here! Would be great if you could add a `readme.md` which will help others to better understand your code. Try to add basic info, how to use, etc. Thanks.

2024-10-02 18:31 UTC, tanushrigoel commented
Added readme.md file. Please check now.

2024-10-02 18:32 UTC, tanushrigoel commented
Please add hacktoberfest-accepted labels

2024-10-03 00:27 UTC, FerdausPolok requested changes
I tried to local run your project with VSCode's Go Live feature which runns the `popup.html` into a spesific `port` of my `localhost`. (IDK if that the proper way to run or not, please correct me if I'm wrong. )

Then when I set a time like 1-2 min and then hit `Start` button it shows below error into console and nothing happens:

```
popup.js:45 Uncaught TypeError: Cannot read properties of undefined (reading 'local')
    at HTMLButtonElement.<anonymous> (popup.js:45:18)
```

Could you please look into it first? Thanks.

2024-10-03 00:27 UTC, FerdausPolok commented on applications-code-snippets/javascript-session-manager/README.md
> +- **Simple Interface**: User-friendly design for seamless interaction.
Can we add another header like

## How to run it?

2024-10-03 00:27 UTC, FerdausPolok commented on applications-code-snippets/javascript-session-manager/background.js
> +
```suggestion
  });

```

2024-10-03 00:27 UTC, FerdausPolok commented on applications-code-snippets/javascript-session-manager/manifest.json
> +
```suggestion
  }

```

2024-10-03 00:27 UTC, FerdausPolok commented on applications-code-snippets/javascript-session-manager/styles.css
> +
```suggestion
  }

```

2024-10-03 03:18 UTC, tanushrigoel commented
Please check now

2024-10-04 03:29 UTC, FerdausPolok requested changes
Yeap @tanushrigoel it's working now! Below are some requested improvement point. Please have a look and ask questions if you have any confussions. Thanks.

1. Could you please now remove the older one? Right now I can see there are 2 folders.

2. Also it would be great if you can improve the user experience by starting the timer right after clickinging Start button. Cause when a user clicks on Start button nothing happen, so it's pretty confusion to know if my timer has started or not. Then once I click somewhere else to close the extention and click on it again then I see my timer.  So basically what I'm asking is that, we see the timer imediately reducing time by sec right after user clicks on start. Can you do that?

3. Lastly, it would be great if you can format all the files inside applications-code-snippets\javascript-youtube-session-manager\ using [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

2024-10-04 03:31 UTC, FerdausPolok reviewed
Thanks you for your work so far.

2024-10-04 11:31 UTC, tanushrigoel commented
Thank you for your patience. I have done the necessary changes. Please check now @FerdausPolok

2024-10-04 15:56 UTC, FerdausPolok reviewed
Cool! Great work @tanushrigoel! 🚀

Btw we can enhance the user experience by addressing this issue:

When a timer is set (e.g., 1 minute), the + and - buttons can still be clicked, but their functionality is missing. The time appears to increase or decrease momentarily, but then resets to the last counted time.

To fix this, we could do a few things:

1. **Add functionality to adjust the time:** Allow the time to increase or decrease while the timer is running. However, if the timer is below 1 minute (e.g., 50 seconds), the - button should be disabled since the time can't go below 0.

3. **Disable the + and - buttons after starting the timer:** Once the timer starts, disable both buttons. Add a "Reset" button next to "Start" so the user can cancel the current timer and set a new one if needed.

If you'd like to include these improvements in the current PR, that would be great. But if you prefer to create a new issue and submit another PR, that's fine too. Let me know how you'd like to proceed. Thanks!

2024-10-04 17:59 UTC, tanushrigoel commented
I will just update this pr and submit it after updating if it's fine

2024-10-05 02:23 UTC, FerdausPolok approved these changes

2024-10-05 02:25 UTC, FerdausPolok commented
> I will just update this pr and submit it after updating if it's fine

Okay then feel free to start further working by creating an issue first. Thanks.

2024-10-05 02:25 UTC, merged